version: '2'

services:
  serveo:
    image: taichunmin/serveo-server:latest
    tty: true
    stdin_open: true
    ports:
      - "2222:2222"
    volumes:
      - "./data/.ssh:/root/.ssh"
    command: >
      serveo
      -port=22
      -http_port=80
      -https_port=443
      -private_key_path=/root/.ssh/id_ed25519
      -domain ds48w8sog4o400cgc8wgo800.57.129.132.234.sslip.io
    labels:
      - "coolify.managed=true"
      - "coolify.applicationId=5"
      - "coolify.type=application"
      - "traefik.enable=true"
      - "traefik.http.routers.serveo.rule=Host(`ds48w8sog4o400cgc8wgo800.57.129.132.234.sslip.io`)"
      - "traefik.http.routers.serveo.entrypoints=http,https"
      - "traefik.http.routers.serveo.tls=true"
